=== rafaelbr/pawprint-genome-datalake/config/schemas/dataset_report_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "accession": {
      "type": "string"
    },
    "current_accession": {
      "type": "string"
    },
    "paired_accession": {
      "type": "string"
    },
    "source_database": {
      "type": "string"
    },
    "organism": {
      "type": "object",
      "properties": {
        "tax_id": {
          "type": "integer"
        },
        "sci_name": {
          "type": "string"
        },
        "organism_name": {
          "type": "string"
        },
        "common_name": {
          "type": "string"
        },
        "lineage": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "tax_id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              }
            }
          }
        },
        "strain": {
          "type": "string"
        },
        "pangolin_classification": {
          "type": "string"
        },
        "infraspecific_names": {
          "type": "object",
          "properties": {
            "breed": {
              "type": "string"
            },
            "cultivar": {
              "type": "string"
            },
            "ecotype": {
              "type": "string"
            },
            "isolate": {
              "type": "string"
            },
            "sex": {
              "type": "string"
            },
            "strain": {
              "type": "string"
            }
          }
        }
      }
    },
    "assembly_info": {
      "type": "object",
      "properties": {
        "assembly_level": {
          "type": "string"
        },
        "assembly_status": {
          "type": "string"
        },
        "paired_assembly": {
          "type": "object",
          "properties": {
            "accession": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "annotation_name": {
              "type": "string"
            },
            "only_genbank": {
              "type": "string"
            },
            "only_refseq": {
              "type": "string"
            },
            "changed": {
              "type": "string"
            },
            "manual_diff": {
              "type": "string"
            }
          }
        },
        "assembly_name": {
          "type": "string"
        },
        "assembly_type": {
          "type": "string"
        },
        "bioproject_lineage": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "bioprojects": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "accession": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "parent_accession": {
                      "type": "string"
                    },
                    "parent_accessions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "bioproject_accession": {
          "type": "string"
        },
        "submission_date": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "submitter": {
          "type": "string"
        },
        "refseq_category": {
          "type": "string"
        },
        "synonym": {
          "type": "string"
        },
        "linked_assembly": {
          "type": "string"
        },
        "linked_assemblies": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "linked_assembly": {
                "type": "string"
              },
              "assembly_type": {
                "type": "string"
              }
            }
          }
        },
        "atypical": {
          "type": "object",
          "properties": {
            "is_atypical": {
              "type": "boolean"
            },
            "warnings": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "genome_notes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sequencing_tech": {
          "type": "string"
        },
        "assembly_method": {
          "type": "string"
        },
        "biosample": {
          "type": "object",
          "properties": {
            "accession": {
              "type": "string"
            },
            "last_updated": {
              "type": "string"
            },
            "publication_date": {
              "type": "string"
            },
            "submission_date": {
              "type": "string"
            },
            "sample_ids": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "db": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              }
            },
            "description": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "organism": {
                  "type": "object",
                  "properties": {
                    "tax_id": {
                      "type": "integer"
                    },
                    "sci_name": {
                      "type": "string"
                    },
                    "organism_name": {
                      "type": "string"
                    },
                    "common_name": {
                      "type": "string"
                    },
                    "lineage": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "tax_id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "strain": {
                      "type": "string"
                    },
                    "pangolin_classification": {
                      "type": "string"
                    },
                    "infraspecific_names": {
                      "type": "object",
                      "properties": {
                        "breed": {
                          "type": "string"
                        },
                        "cultivar": {
                          "type": "string"
                        },
                        "ecotype": {
                          "type": "string"
                        },
                        "isolate": {
                          "type": "string"
                        },
                        "sex": {
                          "type": "string"
                        },
                        "strain": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "comment": {
                  "type": "string"
                }
              }
            },
            "owner": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "contacts": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "lab": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            },
            "models": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "bioprojects": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "accession": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "parent_accession": {
                    "type": "string"
                  },
                  "parent_accessions": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "package": {
              "type": "string"
            },
            "attributes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              }
            },
            "status": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "when": {
                  "type": "string"
                }
              }
            }
          }
        },
        "blast_url": {
          "type": "string"
        },
        "comments": {
          "type": "string"
        },
        "suppression_reason": {
          "type": "string"
        },
        "diploid_role": {
          "type": "string"
        }
      }
    },
    "assembly_stats": {
      "type": "object",
      "properties": {
        "total_number_of_chromosomes": {
          "type": "integer"
        },
        "total_sequence_length": {
          "type": "string"
        },
        "total_ungapped_length": {
          "type": "string"
        },
        "number_of_contigs": {
          "type": "integer"
        },
        "contig_n50": {
          "type": "integer"
        },
        "contig_l50": {
          "type": "integer"
        },
        "number_of_scaffolds": {
          "type": "integer"
        },
        "scaffold_n50": {
          "type": "integer"
        },
        "scaffold_l50": {
          "type": "integer"
        },
        "gaps_between_scaffolds_count": {
          "type": "integer"
        },
        "number_of_component_sequences": {
          "type": "integer"
        },
        "gc_count": {
          "type": "string"
        },
        "gc_percent": {
          "type": "integer"
        },
        "genome_coverage": {
          "type": "string"
        },
        "number_of_organelles": {
          "type": "integer"
        }
      }
    },
    "organelle_info": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "assembly_name": {
            "type": "string"
          },
          "infraspecific_name": {
            "type": "string"
          },
          "bioproject": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          },
          "total_seq_length": {
            "type": "string"
          },
          "submitter": {
            "type": "string"
          }
        }
      }
    },
    "annotation_info": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "release_date": {
          "type": "string"
        },
        "report_url": {
          "type": "string"
        },
        "stats": {
          "type": "object",
          "properties": {
            "gene_counts": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "protein_coding": {
                  "type": "integer"
                },
                "non_coding": {
                  "type": "integer"
                },
                "pseudogene": {
                  "type": "integer"
                },
                "other": {
                  "type": "integer"
                }
              }
            }
          }
        },
        "busco": {
          "type": "object",
          "properties": {
            "busco_lineage": {
              "type": "string"
            },
            "busco_ver": {
              "type": "string"
            },
            "complete": {
              "type": "integer"
            },
            "single_copy": {
              "type": "integer"
            },
            "duplicated": {
              "type": "integer"
            },
            "fragmented": {
              "type": "integer"
            },
            "missing": {
              "type": "integer"
            },
            "total_count": {
              "type": "string"
            }
          }
        },
        "method": {
          "type": "string"
        },
        "pipeline": {
          "type": "string"
        },
        "software_version": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "release_version": {
          "type": "string"
        }
      }
    },
    "wgs_info": {
      "type": "object",
      "properties": {
        "wgs_project_accession": {
          "type": "string"
        },
        "master_wgs_url": {
          "type": "string"
        },
        "wgs_contigs_url": {
          "type": "string"
        }
      }
    },
    "type_material": {
      "type": "object",
      "properties": {
        "type_label": {
          "type": "string"
        },
        "type_display_text": {
          "type": "string"
        }
      }
    },
    "checkm_info": {
      "type": "object",
      "properties": {
        "checkm_marker_set": {
          "type": "string"
        },
        "checkm_species_tax_id": {
          "type": "integer"
        },
        "checkm_marker_set_rank": {
          "type": "string"
        },
        "checkm_version": {
          "type": "string"
        },
        "completeness": {
          "type": "integer"
        },
        "contamination": {
          "type": "integer"
        },
        "completeness_percentile": {
          "type": "integer"
        }
      }
    },
    "average_nucleotide_identity": {
      "type": "object",
      "properties": {
        "taxonomy_check_status": {
          "type": "string"
        },
        "match_status": {
          "type": "string"
        },
        "submitted_organism": {
          "type": "string"
        },
        "submitted_species": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "submitted_ani_match": {
          "type": "object",
          "properties": {
            "assembly": {
              "type": "string"
            },
            "organism_name": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "ani": {
              "type": "integer"
            },
            "assembly_coverage": {
              "type": "integer"
            },
            "type_assembly_coverage": {
              "type": "integer"
            }
          }
        },
        "best_ani_match": {
          "type": "object",
          "properties": {
            "assembly": {
              "type": "string"
            },
            "organism_name": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "ani": {
              "type": "integer"
            },
            "assembly_coverage": {
              "type": "integer"
            },
            "type_assembly_coverage": {
              "type": "integer"
            }
          }
        },
        "comment": {
          "type": "string"
        }
      }
    }
  }
}

=== rafaelbr/pawprint-genome-datalake/sample_data/sample_datasetreport.json
{
   "accession":"GCA_014108235.1",
   "current_accession":"GCA_014108235.1",
   "paired_accession":"GCF_014108235.1",
   "source_database":"SOURCE_DATABASE_GENBANK",
   "organism":{
      "tax_id":51298,
      "organism_name":"Myotis myotis",
      "infraspecific_names":{
         "isolate":"mMyoMyo1",
         "sex":"female"
      }
   },
   "assembly_info":{
      "assembly_level":"Scaffold",
      "assembly_status":"current",
      "paired_assembly":{
         "accession":"GCF_014108235.1",
         "status":"current",
         "annotation_name":"NCBI Myotis myotis Annotation Release 100",
         "changed":"chromosome MT."
      },
      "assembly_name":"mMyoMyo1.p",
      "assembly_type":"haploid",
      "bioproject_lineage":[
         {
            "bioprojects":[
               {
                  "accession":"PRJNA628559",
                  "title":"Myotis myotis isolate:mMyoMyo1 Genome sequencing and assembly",
                  "parent_accessions":[
                     "PRJNA489245",
                     "PRJNA674393"
                  ]
               },
               {
                  "accession":"PRJNA489245",
                  "title":"Bat1K Project",
                  "parent_accessions":[
                     "PRJNA533106"
                  ]
               },
               {
                  "accession":"PRJNA533106",
                  "title":"Earth BioGenome Project (EBP)"
               },
               {
                  "accession":"PRJNA674393",
                  "title":"Myotis myotis Umbrella project",
                  "parent_accessions":[
                     "PRJNA489243"
                  ]
               },
               {
                  "accession":"PRJNA489243",
                  "title":"Vertebrate Genomes Project",
                  "parent_accessions":[
                     "PRJNA533106"
                  ]
               },
               {
                  "accession":"PRJNA533106",
                  "title":"Earth BioGenome Project (EBP)"
               }
            ]
         }
      ],
      "bioproject_accession":"PRJNA628559",
      "release_date":"2020-08-13",
      "submitter":"Bat1K",
      "sequencing_tech":"PacBio Sequel CLR; 10X Genomics chromium linked reads; Bionano Genomics; Phase Genomics HiC; PacBio Sequel IsoSeq",
      "assembly_method":"DAmar v. APRIL-2019; Bionano Solve DLS v. 3.3; Salsa2 HiC v. git commit: e3ae7d8; GenomicConsensus v. git commit: 038de5c; longranger align v. 2.2.0; Freebayes v. 1.2.0; HiGlass manual curation v. 1.5",
      "biosample":{
         "accession":"SAMN14734277",
         "last_updated":"2020-05-05T09:07:47.809",
         "publication_date":"2020-04-27T00:00:00.000",
         "submission_date":"2020-04-27T02:18:04.800",
         "sample_ids":[
            {
               "label":"Sample name",
               "value":"Myotis myotis (Greater mouse-eared bat) for Bat1K reference genome"
            },
            {
               "db":"SRA",
               "value":"SRS6571162"
            }
         ],
         "description":{
            "title":"Animal sample from Myotis myotis",
            "organism":{
               "tax_id":51298,
               "organism_name":"Myotis myotis"
            },
            "comment":"The greater mouse-eared bat (Myotis myotis) is a European species of bat in the family Vespertilionidae. The sample was collected by Emma Teeling and Sebastien Puechmaille from University College Dublin. This sample is being used to generate chromosomal level reference assembly as part of the Bat1K Project."
         },
         "owner":{
            "name":"Max Planck Institute of Molecular Cell Biology and Genetics",
            "contacts":[
               {

               }
            ]
         },
         "models":[
            "Model organism or animal"
         ],
         "bioprojects":[
            {
               "accession":"PRJNA628559"
            }
         ],
         "package":"Model.organism.animal.1.0",
         "attributes":[
            {
               "name":"isolate",
               "value":"mMyoMyo1"
            },
            {
               "name":"dev_stage",
               "value":"adult"
            },
            {
               "name":"sex",
               "value":"female"
            },
            {
               "name":"tissue",
               "value":"flight muscle"
            },
            {
               "name":"biomaterial_provider",
               "value":"Emma Teeling, University College Dublin, School of Biology and Environmental Science, Science Centre - West Belfield Dublin 4"
            },
            {
               "name":"birth_date",
               "value":"unknown"
            },
            {
               "name":"collected_by",
               "value":"Emma Teeling, Sebastien Puechmaille"
            },
            {
               "name":"collection_date",
               "value":"2015"
            },
            {
               "name":"geo_loc_name",
               "value":"France: Limerzel"
            },
            {
               "name":"lat_lon",
               "value":"47.6333 N 2.3500 W"
            },
            {
               "name":"store_cond",
               "value":"SNAP frozen"
            }
         ],
         "status":{
            "status":"live",
            "when":"2020-04-27T02:18:04.803"
         }
      },
      "blast_url":"https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch&PROG_DEF=blastn&BLAST_SPEC=GDH_GCA_014108235.1"
   },
   "assembly_stats":{
      "total_sequence_length":"2002780556",
      "total_ungapped_length":"1973827151",
      "number_of_contigs":630,
      "contig_n50":12511134,
      "contig_l50":41,
      "number_of_scaffolds":92,
      "scaffold_n50":94448911,
      "scaffold_l50":7,
      "number_of_component_sequences":92,
      "gc_count":"850908054",
      "gc_percent":43,
      "genome_coverage":"90.9x",
      "number_of_organelles":1
   },
   "organelle_info":[
      {
         "description":"Mitochondrion",
         "total_seq_length":"17320",
         "submitter":"Bat1K"
      }
   ],
   "annotation_info":{
      "name":"Annotation submitted by Bat1K",
      "provider":"Bat1K",
      "release_date":"2020-08-07",
      "stats":{
         "gene_counts":{
            "total":21284,
            "protein_coding":21284
         }
      }
   },
   "wgs_info":{
      "wgs_project_accession":"JABWUV01",
      "master_wgs_url":"https://www.ncbi.nlm.nih.gov/nuccore/JABWUV000000000.1",
      "wgs_contigs_url":"https://www.ncbi.nlm.nih.gov/Traces/wgs/JABWUV01"
   }
}
